# Generated by Django 4.2 on 2024-04-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
    ]
