# Generated by Django 4.2 on 2024-04-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20240420_2143'),
    ]

    operations = [
    ]
